variables:
- group: EnvironmentVariables
- name:  DOTNET_SDK_VERSION 
  value: '3.0.100'
- name:  DOTNET_PACKAGE_TYPE
  value: 'sdk'
- name:  RUBY_VERSION
  value: '2.5'

  
jobs:
- template: build/tmpl/jobs.yml
  parameters:
    name: macOS
    vmImage: 'macOS 10.13'
    installRuby: 'false'

- template: build/tmpl/jobs.yml
  parameters:
    name: Linux
    vmImage: 'Ubuntu 18.04'

- template: build/tmpl/jobs.yml
  parameters:
    name: Windows
    vmImage: 'VS2017-Win2016'

