variables:
  DOTNET_SDK_VERSION: '3.0.100'
  DOTNET_PACKAGE_TYPE: 'sdk'
  RUBY_VERSION: '2.5'
  group: EnvironmentVariables
  
jobs:
- template: build/tmpl/jobs.yml
  parameters:
    name: macOS
    vmImage: 'macOS 10.13'
    installRuby: 'false'

- template: build/tmpl/jobs.yml
  parameters:
    name: Linux
    vmImage: 'Ubuntu 18.04'

- template: build/tmpl/jobs.yml
  parameters:
    name: Windows
    vmImage: 'VS2017-Win2016'

